### PR TITLE
Fix wrong value for lteq_datetime predicate

### PR DESCRIPTION
**Pull request by workgena**
[refs #61]

### CODE REVIEW

**Comment by workgena** [comment]
image

**Comment by workgena** [comment]
I only don't like the situation with timezones(client and server).

Current situation: The browser sends selected time, and this time will be passed to SQL query as is. The user should know what timezone database-server uses, usually it is UTC.

This is common misunderstanding situation. And I don't know how to handle it. Or it is not the responsibility of a this plugin?

**Comment by workgena** [comment]
@senid231 @Fivell perhaps you have better solution? Feel free to change/add/replace the PR.

**Comment by Fivell** [comment]
@workgena searching should be performed  in the same timezone by default, not sure why not :)

**Comment by workgena** [comment]
After some research I'm intent to merge current solution. It fixes the problem with 


```ruby
  config.add_predicate 'lteq_datetime',
  	arel_predicate: 'lt',
  	formatter: ->(v) { v + 1.day }
```

https://github.com/activeadmin/activeadmin/blob/a496b8c74356880bab934202994ac43117752e54/lib/ransack_ext.rb#L17-L19

The problem with timezone is complicated and is out of scope #61 , so it would be better to solve it in another PR.

**Comment by workgena** [comment]
### NOTICE:

With this change we introduce new predicate `gteq_datetime_picker`. It means the HTML will be different from previous versions:

```html
<!-- old -->
<input id="q_created_at_gteq_datetime">

<!-- new -->
<input id="q_created_at_gteq_datetime_picker">
```

If somebody relies on this in Capybara tests, then such tests should be updated.

**Review by Fivell — APPROVED** [review]

**Pull request merged**
