### PR TITLE
Fix missing CSS-styling in production mode

### PR DESCRIPTION
**Pull request by workgena**
This PR is intended to fix styling error:

| before | after |
|:---:|:---:|
| Before | After |

- [x] Add Rails 5,2 and ActiveAdmin 1.3 to TravisCI
- [x] Fix spec with new CSS injection
- [x] Update README

### CODE REVIEW

**Comment by workgena** [comment]
@Fivell can you please check out why Travis CI does not run?

> Expected — Waiting for status to be reported

**Comment by Fivell** [comment]
@workgena this is github issue , they have some problems now https://twitter.com/githubstatus

**Comment by workgena** [comment]
Looks like we have deprecated(not supported) configuration of Travis:

https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/

> As of May 2, 2018 we are moving toward having repositories integrated via a GitHub App instead of GitHub Services which will **no longer be supported as of October 1, 2018**.

**Comment by Fivell** [comment]
@workgena  are u able to migrate ?

**Comment by workgena** [comment]
@Fivell not, I can't login to Travis "activeadmin-plugins" namespace

**Comment by workgena** [comment]
The problem was with `bin/rails assets:precompile`. It loses the content of "jquery.xdan.datetimepicker.css". The only working solution, I managed to find, is to use ActiveAdmin `register_stylesheet` method. It is DEPRECATED and will be removed in 2.0 version. But, for now, it works correctly. So I propose to use it.

```ruby
# config/initializers/active_admin_datetimepicker.rb
ActiveAdmin.setup do |config|
  config.register_stylesheet 'jquery.xdan.datetimepicker.css'
end
```

**Review by Fivell — APPROVED** [review]

**Comment by Fivell** [comment]
@workgena  👍 feel free to bump new version

**Comment by benjaminwood** [comment]
FYI, it's not released yet but active admin has undeprecated `register_stylesheet`

https://github.com/activeadmin/activeadmin/pull/5662

Guess it paid off to wait until active_admin provided a 'solution' :smile:

**Pull request merged**
