### PR TITLE
Update gemspec to work with AA 1.2.1

### PR DESCRIPTION
**Pull request by JNajera**
👍

### CODE REVIEW

**Comment by Fivell** [comment]
@JNajera thanks , please squash commits into a single one

**Comment by JNajera** [comment]
Sorry for the mess, now its on a single commit.

**Review by Fivell — APPROVED** [review]

**Comment by yaaase** [comment]
any chance this can be merged? we'd love to keep using this gem

**Comment by workgena** [comment]
I'll take a look today. Simply lost this PR

**Comment by workgena** [comment]
PR moved to #41, I wanted to make it compatible with 1.1.0, so make a little tweak.

@JNajera @yaaase thanx for help/support :sun_with_face:

New release **0.6.2** is out on [RubyGems](https://rubygems.org/gems/active_admin_datetimepicker)

**Pull request closed without merging**
