### PR TITLE
Add data datepicker_options for DateTimeRangeInput, default time form…

### PR DESCRIPTION
**Pull request by workgena**
Fix bug when DateTimeRangeInput does not has datepicker_options. In same way as single-DateTimePickerInput.

### CODE REVIEW

**Comment by Fivell** [comment]
@workgena , can you pls make it more DRY?

**Comment by workgena** [comment]
@Fivell, check new version

**Comment by Fivell** [comment]
@workgena , please squash you commits in single one

**Comment by workgena** [comment]
With this PR now it is possible to override options. For example if you need date-time with seconds, all you need is to add file

```
/config/initializer/active_admin_datetimepicker.rb
```

``` ruby
# This if for fornt-end javascript side
ActiveAdminDatetimepicker::Base.default_datetime_picker_options = {
    format: 'Y-m-d H:i:s',
    defaultDate: proc { DateTime.now.utc.strftime('%y-%m-%d') }
}
# This if for backend(Ruby)
ActiveAdminDatetimepicker::Base.format = "%Y-%m-%d %H:%M:%S"
```

"default_datetime_picker_options" is XDSoft's DateTime picker options. So you can pass any other options same way. 
Full options list: http://xdsoft.net/jqplugins/datetimepicker/

I recomend add this to README.

**Comment by Fivell** [comment]
:+1:

**Pull request merged**
